<?php
/**
 * Created by PhpStorm.
 * User: RachelWaffle
 * Date: 15/12/23
 * Time: 上午11:38
 */

include_once 'cores/themes.php';

function featured_display_block_info()
{

    $blocks['display_resource'] = get_blocks('Display Resource');
    $blocks['display_application'] = get_blocks('Display Application');
    $blocks['display_trade'] = get_blocks('Display Trade');
    $blocks['display_perception'] = get_blocks('Display Perception');
    $blocks['login_bar'] = get_blocks('Login Bar');
    return $blocks;
}


function featured_display_page_build()
{
    drupal_add_css(drupal_get_path('module', 'featured_display') . '/css/featured_display.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

/**
 * Implements hook_block_view
 */
function featured_display_block_view($delta = '')
{
    switch ($delta) {
        case 'display_resource': // 如果调用了数据资源
            if (user_access('access content')) {
                $category='数据资源';
                $content_getter = new ContentGetter();
                $content_wrap = new ContentData();
                $content_getter->add_wrapped_div($content_wrap,'','con con3bg');
                $content_getter->add_wrapped_div($content_wrap,'','con3');
                $content_getter->add_content($content_wrap,'<div style="height:0px; overflow:hidden;">&nbsp;</div>');
                $content_getter->add_head($content_wrap,'数据资源',3,'c31');
                $content_getter->add_head($content_wrap,'提供各行业数据资源，以及大数据分析处理能力',4,'c32');

                $content_data= new ContentData();
                $content_getter->add_wrapped_div($content_data,'','c33');
                foreach(variable_get('data_resource_data') as $item){
                    $content_getter->get_resource_content($content_data,$item);
                }
                $content_getter->add_content($content_wrap,$content_getter->execute($content_data));

                $content_getter->add_content($content_wrap,$content_getter->get_more_button('数据资源'));
                $data = $content_getter->execute($content_wrap);
                $block['content'] = $data;
                unset($content_getter);
                unset($content_wrap);
                unset($content_data);
                return $block;

            }
            break;

        case 'display_application': // 如果调用了数据应用
            if (user_access('access content')) {

                $category = '数据应用';
                $content_getter = new ContentGetter();
                $content_wrap = new ContentData();

                $content_getter->add_wrapped_div($content_wrap,'','con con4bg');
                $content_getter->add_wrapped_div($content_wrap,'','con4');
                $content_getter->add_content($content_wrap,'<div style="height:0px; overflow:hidden;">&nbsp;</div>');
                $content_getter->add_image($content_wrap,cqtheme_get_path().'/img/arrow_4.png','',' class="arr"');
                $content_getter->add_head($content_wrap,'数据应用',3,'c41');

                $content_data= new ContentData();
                $content_getter->get_application_content($content_data);
                //取出的数据添加到主内容
                $content_getter->add_content($content_wrap,$content_getter->execute($content_data));
                //添加『更多』按钮
                $content_getter->add_content($content_wrap,$content_getter->get_more_button($category));

                $block['content'] = $content_getter->execute($content_wrap);
                unset($content_getter);
                unset($content_wrap);
                unset($content_data);
                return $block;
            }
            break;

        case 'display_trade' : // 如果调用了数据交易
            if (user_access('access content')) {
                $content_getter = new ContentGetter();
                $content_wrap = new ContentData();
                $content_wrap_2 = new ContentData();
                $content_data = new ContentData();

                $content_getter->add_wrapped_div($content_wrap,'','con con5bg');
                $content_getter->add_wrapped_div($content_wrap,'','con5');
                $content_getter->add_content($content_wrap,'<div style="height:0px; overflow:hidden;">&nbsp;</div>');
                $content_getter->add_image($content_wrap,cqtheme_get_path().'/img/arrow_5.png','',' class="arr"');
                $content_getter->add_head($content_wrap,'数据交易',3,'c51');

                $content_getter->add_wrapped_div($content_wrap_2,'','c52');

                $content_getter->add_content($content_wrap_2,$content_getter->get_trade_content($content_data,'数据下载排行',array('theme'=>'ordered_ul','max_length'=>20))) ;
                $content_getter->add_content($content_wrap_2,$content_getter->get_trade_content($content_data,'最新发布数据',array('theme'=>'time_ul','max_length'=>14))) ;
                $content_getter->add_content($content_wrap_2,$content_getter->get_trade_content($content_data,'平台动态',array('theme'=>'simple_ul','max_length'=>20),'c52div end'));

                $content_getter->add_content($content_wrap,$content_getter->execute($content_wrap_2));
                $content_getter->add_content($content_wrap,'<p class="c53">注：上述数据已通过重庆政府数据服务网开放，如需下载请登陆 <span>www.datachongqing.gov.cn</span></p>');

                $block['content'] = $content_getter->execute($content_wrap);
                unset($content_getter);
                unset($content_wrap);
                unset($content_wrap_2);
                unset($content_data);
                return $block;

            }
            break;

        case 'display_perception': // 如果调用了物联感知

            if (user_access('access content')) {

                $content_getter = new ContentGetter();
                $content_wrap = new ContentData();
                $content_getter->add_wrapped_div($content_wrap,'','con con6bg');
                $content_getter->add_wrapped_div($content_wrap,'','con6');
                $content_getter->add_content($content_wrap,'<div style="height:0px; overflow:hidden;">&nbsp;</div>');
                $content_getter->add_image($content_wrap,cqtheme_get_path().'/img/arrow_6.png','',' class="arr"');
                $content_getter->add_head($content_wrap,'物联感知',3,'c61');

                $content_data= new ContentData();
                $content_getter->add_wrapped_div($content_data,'','c62');
                foreach(variable_get('data_perception_data') as $item){
                    $content_getter->get_resource_content($content_data,$item);
                }
                $content_getter->add_content($content_wrap,$content_getter->execute($content_data));

                $data = $content_getter->execute($content_wrap);
                $block['content'] = $data;
                unset($content_getter);
                unset($content_wrap);
                unset($content_data);
                return $block;
            }
            break;

        case 'login_bar' :  //登录bar,editor系统跳转
            if (user_is_logged_in()) {
                global $user;
                $userRole = '';
                $sysUrl = 'http://www.microsoft.com/index.aspx?userid='.$user->uid.'&username='.$user->name;
                $block['content'] = '<ul class="loginbar">';
                
                if (in_array('editor', $user->roles) || in_array('manager', $user->roles)){
                    if ($user->roles[4] == 'manager') {
                        $userRole = 'manager';
                        $sysUrl .= '&roleid=4';
                    } elseif ($user->roles[5] == 'editor') {
                        $userRole = 'editor';
                        $sysUrl .= '&roleid=5';
                    }
                    if(!empty($userRole)) {
                        $block['content'] .= '<li>'.'<a href="'.$sysUrl.'">系统对接</a>'.'</li>';
                    }
                }
                
                
                //如果登录了
                $block['content'] .= '<li>'.l(t('My account'),drupal_get_path_alias('user')).'</li>'.'<li>'.l(t('Log out'),drupal_get_path_alias('user/logout')).'</li>'.'</ul>';
                
                return $block;
            } else {
                //如果未登录
                $block['content']='<ul class="loginbar"><li>'.l(t('User login'),drupal_get_path_alias('user/login')).'</li><li>'.l(t('Create new account'),drupal_get_path_alias('user/register')).'</li></ul>';
                return $block;
            }

            break;
        default :
            ;
    }

}


function cqtheme_get_path(){

    return drupal_get_path('theme','cqtheme');
}

//variable_set('data_resource_data',array(
//    array('name'=>'医疗卫生','category'=>'医疗卫生','img'=>cqtheme_get_path().'/img/3-1-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'社会保障','category'=>'社会保障','img'=>cqtheme_get_path().'/img/3-2-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'教育文化','category'=>'教育文化','img'=>cqtheme_get_path().'/img/3-3-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'交通旅游','category'=>'交通旅游','img'=>cqtheme_get_path().'/img/3-4-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'资源环境','category'=>'资源环境','img'=>cqtheme_get_path().'/img/3-5-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'工业经济','category'=>'工业经济','img'=>cqtheme_get_path().'/img/3-6-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'农业生产','category'=>'农业生产','img'=>cqtheme_get_path().'/img/3-7-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'商贸物流','category'=>'商贸物流','img'=>cqtheme_get_path().'/img/3-8-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'公共安全','category'=>'公共安全','img'=>cqtheme_get_path().'/img/3-9-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//    array('name'=>'社会生活','category'=>'社会生活','img'=>cqtheme_get_path().'/img/3-10-n.png','head_class'=>'c33divt','div_class'=>'c33div','img_class'=>'c33divimg','des_class'=>'c33divp'),
//));
//
//variable_set('data_perception_data',array(
//    array('name'=>'农业类','category'=>'农业类','img'=>cqtheme_get_path().'/img/6-1-n.png','head_class'=>'c62h4','div_class'=>'c62div','img_class'=>'c62img','des_class'=>'c62p'),
//    array('name'=>'建筑类','category'=>'建筑类','img'=>cqtheme_get_path().'/img/6-2-n.png','head_class'=>'c62h4','div_class'=>'c62div','img_class'=>'c62img','des_class'=>'c62p'),
//    array('name'=>'医疗类','category'=>'医疗类','img'=>cqtheme_get_path().'/img/6-3-n.png','head_class'=>'c62h4','div_class'=>'c62div','img_class'=>'c62img','des_class'=>'c62p'),
//
//));

function featured_display_menu() {
  $items['verifyuser/userid/%/roleid/%'] = array(
    'title' => 'verify user by external system',
    'page callback' => 'verifyUser',
    'page arguments' => array(2, 4),
    "access callback" => TRUE,
//    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function verifyUser($userid, $roleid) {
    //set external allowed ip
    $allowedIp = '';
    if(ip_address != $allowedIp) {
//        return drupal_json_output(array('status' => FALSE, 'pass' => ''));
    }

    if(!empty($userid) && !empty($roleid)) {
        $account = user_load($userid);
        if ($account->roles[$roleid] == 'manager' || $account->roles[$roleid] == 'editor'){
            return drupal_json_output(array('status' => TRUE, 'pass' => $account->pass));
        }
    } 
    return drupal_json_output(array('status' => FALSE, 'pass' => ''));
}


/**
 * Implements hook_node_view().
 */
function featured_display_node_view($node, $view_mode, $langcode = NULL)
{

    if($view_mode=='full') {
        $field_terms = current($node->field_resource);
        if(!empty($field_terms)) {
            $field_term = current($field_terms);
            $breadcrumb = array();
            if (isset($field_term)) {
                //load taxonomy term
                $term = taxonomy_term_load($field_term['tid']);
                $breadcrumb[] = l(t('Home'), '<front>');
                //add parent taxonomy term
                add_breadcrumb_path($breadcrumb, $field_term['tid']);
                $breadcrumb[] = l(t($term->name), drupal_get_path_alias('taxonomy/term/' . $field_term['tid']));
                // Set Breadcrumbs
                drupal_set_breadcrumb($breadcrumb);
            }
            $node->breadcrumbs = theme('breadcrumb', array('breadcrumb' => drupal_get_breadcrumb()));
        }
    }
}



/**
 * find all parents and add to breadcrumb path
 */
function add_breadcrumb_path(&$breadcrumb,$tid){
    $parents=taxonomy_get_parents($tid);
    if(!empty($parents)){
        $parent = current($parents);
        add_breadcrumb_path($breadcrumb,$parent->tid);
        $breadcrumb[]= l(t($parent->name),drupal_get_path_alias('taxonomy/term/'.$parent->tid));
    }
}
